version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /api
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /auth
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /store
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /store/backend
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /links
    schedule:
      interval: monthly
